language: scala
sudo: false

# Main Scala version
scala:
- 2.12.8

jdk:
- openjdk8

before_install:
- "[ -z \"${encrypted_316f730cabee_iv}\" ] || openssl aes-256-cbc -K $encrypted_316f730cabee_key -iv $encrypted_316f730cabee_iv -in ./project/secrets.tar.xz.enc -out ./project/secrets.tar.xz -d"
- "[ -z \"${encrypted_316f730cabee_iv}\" ] || tar xfvJ project/secrets.tar.xz -C project"
- git fetch --tags
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.4.4 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.3

stages:
- name: test
- name: microsite
- name: release
  if: (branch = master AND type = push) OR (tag IS present)
# Remove once there is a Monix release for 2.13
- name: releaseMonix
  if: (branch = master AND type = push) OR (tag IS present)
- name: publishMicrosite
  if: tag IS present

jobs:
  include:
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck unusedCompileDependenciesTest
    - &test
      stage: test
      name: "Test for 2.12"
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - &scaladoc
      stage: microsite
      name: "Generate Scaladoc"
      script: sbt ++$TRAVIS_SCALA_VERSION coreJVM/doc coreJS/doc interopCatsJVM/doc interopCatsJS/doc interopFutureJVM/doc interopFutureJS/doc interopScalaz7xJVM/doc interopScalaz7xJS/doc interopMonixJVM/doc interopMonixJS/doc interopJavaJVM/doc
    - &microsite
      stage: microsite
      name: "Generate microsite"
      script: sbt ++$TRAVIS_SCALA_VERSION microsite/makeMicrosite
    - &release
      stage: release
      name: "Release artifacts"
      before_script: export PGP_SECRET="$(<./project/zecret)"
      script: sbt ci-release || sbt sonatypeReleaseAll
    - &releaseMonix
      stage: releaseMonix
      name: "Release interop-monix"
      script: sbt publishSigned sonatypeRelease
    - &publishSite
      stage: publishMicrosite
      name: "Publish microsite"
      before_script:
      - cp ./project/travis-deploy-key ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      script:
      - git config --global user.email "tim@nequissimus.com"
      - git config --global user.name "Tim Steinbach"
      - git config --global push.default simple
      - sbt ++$TRAVIS_SCALA_VERSION microsite/publishMicrosite

    # Cross-build
    - <<: *test
      scala: 2.13.0-M5
      name: "Test for 2.13"

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.rvm

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

env:
  global:
  - secure: 1KShGbny4TgD86w5/huvJEwcLYEQKjiUZeornS8W0rt8+j2emfFpb2VoyCfOQmXQrh0t5N96dS/hT0C+cDE0+/12rOE4zpm5RDDT7skY+ayTb3SKkIP9Qk5behvyIZi8xc5ny6z6UZoFBeTGJMZQgeuADhfcQHw68cZl4kEM9fU8L6Yc8jKUN6xTENnVpIDmM29Tbx/WyNA9EKw+1CL2fJVVLmvsQphieYoVjQfhZjl1+M289cZ+dX1UjsuvfrfwBTwFoabnZbQATZ9ALvwIfuOKYIdapS3rAayaKC7uihWZmCnNT4mmleob+zXdUjOWl/GXlHAgeCWU1GP7qZ65aLRx+URs/Vh+VAi5gXceF9Mka0VYMb/nm+noJIy9WLKa4kfnHruqR5NzxTq8D0xkgSa2v1tRCT7Vf98+RlzPTVF+rG/8lGa/nFoxqAkbB8ycTYSoAIswan4lx2PhD2GPWsCdiUBrMljPTr2ie88x45w4b5f5eZbsxc1qi2ks1oFTVJhk36l9+E+V8iFi3uZbs2x5Qfar7301mWwarcwfxt/CgDqSz4naWXyPfRbh9KwwFnjl2yEiYoPb0zU8eKhBid+JBi94gvlm2ykmHTYWD39govSgW69PSBoW8JROE10skpiLFsowe/U6FkVNA+tWavk/PNHPpHb4dlP63mbiOTU=
  - secure: RC4sr+jES1TmvcYaTLlPEFjf5HRjNqO5oKS8NtmqNfjcnyiQu/xDfGYQ3cy7hJ3oX4PlzZMaCpA9FEq4/PNT5CwoZcwUPUsNLAsGpn4he/y/4gWURrsI/0G0dtTRcu6NHvl7kL2o+SWQZD1qMOgwcdwj2bw5fqbPtRKAVYadS/oYvb9XnZsIgC7wGzpAY0L/RFh/KifCl6n1gRl28/6TP1lx8Au6UpKjMfKVQcNcoZKERQCyrVhjeqWFwQiZP+7wHFyFoi717wJLMN7eRLxts2xC0lyYOfQlWSrH4jB1XikPfJtGgj6nR3FBd6W0RS2ekmG/ILNnpiIrO9OX8cVO2SZ9+xgbdNZCxTc9LHTDpD015n9qgSnpcuZxHMgkU+/R3v80ss/h0EWG/qmh53xNBc5E+rjIKwcVMjlMrNyGad8vpabz3XdOzk67hcRit/pDxEYzcw5VMOv+kxzZWy3u2+obm6bk+JzS30Kw04qneXdHLTbcXLglRoyVKweNR5aINWItLuqhQbpJ1JOjHz+mMhaMeCBLHsyeakipIkRGTmMmuuxpip2AkgYjhC7V8uLhQIitODN6FJ1K5y7UADYHGCsp5+av/cFGVuDnfRV1PRbC7oz5yHkdOopwBFOHqMZ+TmAu5133t5aazVlcHJuoy/Rfplg+pcS+rkoFZcQjVGI=
  - secure: uOBpV23x8GzYIZG9Xe3ENLq8URJgEWCLvdEmpBXkH/6uBFBfISy+Q89OIrnKlw8E6wN8Bl1WGvobAWGUfxZgjaUlpo5psbRw0kqxz8te4DVMNP/vwkwfwDujLCBrdkvTv5uiLvYD+LmDAZ4eeaZHkMSn3dwwQ2R/lQYLuatsvF35B8RIY/0pG8ambMjBa7uVy94sW5bX0oPTkBhC+BGpAJyxH1H+aT4+J0MDT9VnsyJLUEmVX7CAk13GPcEkECZyeIEcCX4AEhc8wyfpPxp+MyvZfUeGVFZm/D/bi7gnpczO3T8LBXX1Pb3g/3K4dlKuw3KxpUZ0eG8E1yMQWcWDu+PSsJ5L/CAckfgvfSF3rCI3M2E6wmYIRLeqtz+FXe8UkUswKMFdny0zUU2Q9f5IlfZfP3tvXBSIawxuInUmbgt84SV165TQW6Z3qMmNm4ujI7ntg027XNHXa3b4vJv4GNaDNGuuJKPLX6/ELiyW/rlnQPusgQ30s1afBd1ZE/cxau7A3y/MPpXxBKe4GrqeoG2oh2Mm7Jl3OEUYZL4c1BDtzDnT8mo0G5BgBPWsov+7ZrPTR/PfQjLSSMbJm/Jf8jGkq3YK70nXOVjbCcHtkPTpp5qI0A/I9nsZkEoVjsyTm2LSJRmE+Ay5D7pvmuA1R5tA4bVYDEiAXnRoxn42dfA=
