name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-20.04
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'scala-steward'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
