name: Auto-approve Renovate's PRs

on: pull_request_target

jobs:
  auto-approve-renovate-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: '0'
      - name: Approve PR
        if: github.actor == 'renovate[bot]'
        run: gh pr review --approve ${{ github.event.number }}
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
