name: Website

on:
  push:
    branches:
      - documentation
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - run: |
          ./scripts/createSite ${{ github.ref }}
      - name: Publish Github pages
        run: |
          ./sbt docs/docusaurusPublishGhpages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
